#!/bin/sh
down() {
    brightnessctl set 13%-
    brightness=$(brightnessctl get)
    max=$(brightnessctl max)
    percent=$(( brightness * 100 / max ))
    dunstify -a "BRIGHTNESS" "Decreasing to $percent%" -h int:value:"$percent" \
        -i ~/.config/dunst/assets/ui/brightness-low.svg -r 2593 -u normal
}
up() {
    brightnessctl set +13%
    brightness=$(brightnessctl get)
    max=$(brightnessctl max)
    percent=$(( brightness * 100 / max ))
    dunstify -a "BRIGHTNESS" "Increasing to $percent%" -h int:value:"$percent" \
        -i ~/.config/dunst/assets/ui/brightness-high.svg -r 2593 -u normal
}
case "$1" in
    up) up ;;
    down) down ;;
esac
